import { Geist, Geist_Mono,JetBrains_Mono,JetBrains_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/ui/Header";
import PageTransition from "@/components/ui/PageTransition";
import StairsTransition from "@/components/ui/StairsTransition";


const jetbrains_Mono = JetBrains_Mono({
  subsets: ["latin"],
  weight: ["100", "200", "300","400","500","600","700","800",],
  variable:'--font-jetbrainsMono'
 })

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={jetbrains_Mono.className}>
         <Header />
         <StairsTransition/>
         <PageTransition>
          {children}
         </PageTransition>
        
        
      </body>
    </html>
  );
}
